- helm v3 chart - fixed helm chart indexing script

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,11 +21,13 @@ jobs:
       - run: yarn install
       - run: yarn build
       - run: yarn test
-      - name: helm-check
-        uses: igabaydulin/helm-check-action@0.1.4
-        env:
-          CHART_LOCATION: ./deploy/magda-csv-connector
-          CHART_VALUES: ./deploy/test-deploy.yaml
+      
+      - name: Setup Helm
+        uses: azure/setup-helm@v1
+        with:
+          version: v3.2.0
+
+      - run: yarn helm-lint
 
       - name: Login to GitHub Package Repository
         env:
@@ -48,11 +50,6 @@ jobs:
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
 
-      - name: Setup Helm
-        uses: azure/setup-helm@v1
-        with:
-          version: v2.16.1
-
       - name: Setup AWS CLi Tools
         uses: chrislennon/action-aws-cli@v1.1
 
@@ -62,10 +59,12 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
-          echo "Sync with existing charts repo in s3..."
-          mkdir -p chart-repo
-          aws s3 sync s3://magda-charts/ chart-repo
-          helm package ./deploy/${REPO_NAME} -d chart-repo --save=false
-          helm repo index chart-repo
-          echo "Releasing charts to s3..."
-          aws s3 sync chart-repo s3://magda-charts/ --acl public-read
+          cd deploy
+          mkdir -p sync_dir
+          mkdir -p index_dir
+          if ! aws s3 cp s3://magda-charts/index.yaml index_dir/index.yaml; then echo "failed to copy current repo index" && exit 1; fi
+          helm package -d sync_dir ${REPO_NAME}
+          helm repo index --merge "index_dir/index.yaml" sync_dir
+          mv -f sync_dir/index.yaml index_dir/index.yaml
+          aws s3 sync sync_dir s3://magda-charts/ --acl public-read
+          aws s3 cp index_dir/index.yaml s3://magda-charts/index.yaml --acl public-read
